code --install-extension 2gua.rainbow-brackets
code --install-extension alefragnani.Bookmarks
code --install-extension annsk.alignment
code --install-extension bernardodsanderson.theme-material-neutral
code --install-extension coolbear.systemd-unit-file
code --install-extension cstrap.python-snippets
code --install-extension DengSir.template-generator-vscode
code --install-extension dongli.python-preview
code --install-extension donjayamanne.jupyter
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension frhtylcn.pythonsnippets
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension ionceflorin.copy-current-file-path
code --install-extension janisdd.vscode-edit-csv
code --install-extension jchannon.csharpextensions
code --install-extension jtr.vscode-position
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-mssql.mssql
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension njpwerner.autodocstring
code --install-extension OpaccSoftwareAG.webapplicationservices
code --install-extension paulhoughton.vscode-jscpd
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-yaml
code --install-extension robert.ruby-snippet
code --install-extension shardulm94.trailing-spaces
code --install-extension swashata.beautiful-ui
code --install-extension TabNine.tabnine-vscode
code --install-extension tht13.python
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscoss.vscode-ansible
code --install-extension wingrunr21.vscode-ruby
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yummygum.city-lights-theme
